// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rpc

import (
	"contentService/internal/rpc"
	"contentService/internal/rpc/datamanager"
	"contentService/pkg/config"
)

// Injectors from wire.go:

func wireRpc() (*rpc.Rpc, func(), error) {
	gConfig := config.NewGConfig()
	mysqlHelper, cleanup, err := datamanager.NewMysqlHelper(gConfig)
	if err != nil {
		return nil, nil, err
	}
	redisHelper, cleanup2, err := datamanager.NewRedisHelper(gConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rpcRpc := rpc.NewRpc(gConfig, mysqlHelper, redisHelper)
	return rpcRpc, func() {
		cleanup2()
		cleanup()
	}, nil
}
