// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"contentService/internal/api"
	"contentService/internal/api/conn"
	"contentService/internal/api/content"
	"contentService/pkg/config"
)

// Injectors from wire.go:

func wireApi() (*api.Api, func(), error) {
	gConfig := config.NewGConfig()
	clientConn, cleanup, err := conn.NewRpcConnClient(gConfig)
	if err != nil {
		return nil, nil, err
	}
	apiContent := content.NewApiContent(clientConn)
	apiApi := api.NewApi(gConfig, apiContent)
	return apiApi, func() {
		cleanup()
	}, nil
}
